language: objective-c

notifications:
  email:
    recipients:
      - info@berndrabe.de
    on_success: [always]
    on_failure: [change]

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xcodebuild clean build -workspace IBANCheck.xcworkspace -scheme IBANCheck -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'
- xctool test -workspace IBANCheck.xcworkspace -scheme IBANCheck -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'

